import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cartify',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='box-border bg-white'>
      <body className='flex flex-col items-center bg-white'>
        {children}
      </body>
    </html>
  )
}
