import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/Header'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cosmic Corner',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='box-border'>
      <body className='flex flex-col items-center'>
        <Header />
        {children}
      </body>
    </html>
  )
}
