import Footer from './components/Footer'
import Header from './components/Header'
import { CartContextProvider } from './context/CartContext'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cartify',
  description: 'Generated by create next app',
  // icons: {
  //   icon: '/images/favicon.ico',
  // },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='box-border'>
      <head>
        <link rel="icon" href="/images/favicon.ico" sizes="any" />
      </head>
      <body className='flex flex-col items-center bg-white h-full'>
        <CartContextProvider>
          <Header />
          {children}
          <Footer />
        </CartContextProvider>
      </body>
    </html>
  )
}
